version: "3.9"
services:
  iam-xray:
    build: .
    container_name: iam-xray
    ports:
      - "8501:8501"
    environment:
      - IAM_XRAY_FERNET_KEY=${IAM_XRAY_FERNET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - KEEP_DAYS=${KEEP_DAYS}
    volumes:
      - ./data:/app/data
    restart: unless-stopped